### ISSUE TITLE
Speaking components-on-a-grid

### ISSUE THREAD

**Issue by haywasta** [haywasta/components-on-a-grid#1]
@thatkidmadrid

I have attached an audio file of myself speaking the CSS for components-on-a-grid for week 2.

[wd2-stacey-johnstone-week2-components-on-a-grid.m4a.zip](https://github.com/haywasta/components-on-a-grid/files/7212434/wd2-stacey-johnstone-week2-components-on-a-grid.m4a.zip)

**Comment by thatkidmadrid** [comment]
Great!
Looks good and sounds good - easy to follow along and understand 👍
